//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileFilterStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileFilterStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Localization.FileFilterStrings", typeof(FileFilterStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afb Texture (*.afb)|*.afb.
        /// </summary>
        public static string Afb {
            get {
                return ResourceManager.GetString("Afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunithm Chart (*.c2s)|*.c2s.
        /// </summary>
        public static string C2S {
            get {
                return ResourceManager.GetString("C2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw Surface (*.dds)|*.dds.
        /// </summary>
        public static string DDS {
            get {
                return ResourceManager.GetString("DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable (*.exe)|*.exe.
        /// </summary>
        public static string Exe {
            get {
                return ResourceManager.GetString("Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png;*.jpg;*.jpeg;*.webp)|*.png;*.jpg;*.jpeg;*.webp.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margrete Chart (*.mgxc)|*.mgxc.
        /// </summary>
        public static string Mgxc {
            get {
                return ResourceManager.GetString("Mgxc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Files (*.wav;*.ogg;*.mp3)|*.wav;*.ogg;*.mp3.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
    }
}
