//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Common.Localization.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file is not set..
        /// </summary>
        public static string Error_audio_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_audio_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File is not set..
        /// </summary>
        public static string Error_background_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_background_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart file is not set..
        /// </summary>
        public static string Error_chart_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_chart_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file was not found: {0}.
        /// </summary>
        public static string Error_file_not_found {
            get {
                return ResourceManager.GetString("Error_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input path is not set..
        /// </summary>
        public static string Error_input_path_is_not_set {
            get {
                return ResourceManager.GetString("Error_input_path_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket file is not set..
        /// </summary>
        public static string Error_jacket_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_jacket_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID is not set..
        /// </summary>
        public static string Error_song_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_song_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID is not set..
        /// </summary>
        public static string Error_stage_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_stage_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Event ID is not set..
        /// </summary>
        public static string Error_we_event_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_we_event_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string Status_converting {
            get {
                return ResourceManager.GetString("Status_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Audio....
        /// </summary>
        public static string Status_converting_audio {
            get {
                return ResourceManager.GetString("Status_converting_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Chart....
        /// </summary>
        public static string Status_converting_chart {
            get {
                return ResourceManager.GetString("Status_converting_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Jacket....
        /// </summary>
        public static string Status_converting_jacket {
            get {
                return ResourceManager.GetString("Status_converting_jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        public static string Status_reading {
            get {
                return ResourceManager.GetString("Status_reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing....
        /// </summary>
        public static string Status_writing {
            get {
                return ResourceManager.GetString("Status_writing", resourceCulture);
            }
        }
    }
}
